"""Markdown export for SDLC artifact documents (Concept Brief)."""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.artifact import (
    ArtifactDocument, CbCapability, CbContextMap, CbGateCriterion,
    CbMetric, CbMilestone, CbOutcome, CbScopeItem, CbTextBlock,
)
from app.models.project import Project


def _esc(text: str) -> str:
    """Escape pipe characters so they don't break Markdown tables."""
    return (text or "—").replace("|", "\\|").replace("\n", " ")


async def export_concept_brief(project_id: uuid.UUID, db: AsyncSession) -> str:
    """Render the Concept Brief as structured Markdown."""
    project = await db.get(Project, project_id)
    if project is None:
        raise ValueError("Project not found")

    doc = (
        await db.execute(
            select(ArtifactDocument).where(
                ArtifactDocument.project_id == project_id,
                ArtifactDocument.artifact_type == "concept_brief",
            )
        )
    ).scalar_one_or_none()
    if doc is None:
        raise ValueError("Concept Brief not found")

    slug = project.name.lower().replace(" ", "-")[:40]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    status = "Validated" if doc.status == "validated" else "Draft"

    # Overall completeness from unit_status
    unit_status = doc.unit_status or {}
    completeness_vals = [v.get("completeness", 0) for k, v in unit_status.items() if isinstance(v, dict) and not k.startswith("_")]
    avg_completeness = round(sum(completeness_vals) / len(completeness_vals)) if completeness_vals else 0
    conf_vals = [v.get("confidence", "low") for k, v in unit_status.items() if isinstance(v, dict) and not k.startswith("_")]
    conf_order = {"low": 0, "medium": 1, "high": 2}
    overall_conf = min(conf_vals, key=lambda c: conf_order.get(c, 0)) if conf_vals else "low"

    async def _text(field_key: str) -> str:
        row = (
            await db.execute(
                select(CbTextBlock).where(
                    CbTextBlock.document_id == doc.id,
                    CbTextBlock.row_key == field_key,
                    CbTextBlock.is_current.is_(True),
                    CbTextBlock.status == "active",
                )
            )
        ).scalar_one_or_none()
        return row.text if row else "—"

    async def _rows(model):
        return (
            await db.execute(
                select(model).where(
                    model.document_id == doc.id,
                    model.is_current.is_(True),
                    model.status == "active",
                ).order_by(model.row_key)
            )
        ).scalars().all()

    L: list[str] = []

    def section(title: str) -> None:
        L.append("")
        L.append("---")
        L.append("")
        L.append(title)
        L.append("")

    # ── Frontmatter ──────────────────────────────────────────────────────────
    L += [
        "---",
        f"title: \"{project.name} – Concept Brief\"",
        f"artefactType: concept-brief",
        f"status: {status}",
        f"completeness: {avg_completeness}%",
        f"confidence: {overall_conf}",
        f"generatedAt: {now}",
        f"project: {project.name}",
        "---",
    ]

    # ── Title & summary callout ───────────────────────────────────────────────
    L += [
        "",
        f"# {project.name}",
        f"## Concept Brief",
        "",
        f"> **Status:** {status} &nbsp;·&nbsp; **Completeness:** {avg_completeness}% &nbsp;·&nbsp; **Confidence:** {overall_conf}  ",
        f"> Generated by SpecForge on {now}",
    ]

    if project.description:
        L += ["", f"_{project.description}_"]

    # ── Document Control ──────────────────────────────────────────────────────
    section("## Document Control")
    L += [
        "| Version | Date | Status |",
        "|:-------:|------|--------|",
    ]
    if doc.validated_at:
        L.append(f"| 1.0 | {doc.validated_at.strftime('%Y-%m-%d')} | Validated |")
    else:
        L.append(f"| 0.1 | {now} | Draft |")

    # ── 1. Problem Statement & Context Map ────────────────────────────────────
    section("## 1. Problem Statement & Context Map")

    L += ["### Business Context", ""]
    L.append(await _text("business_context"))

    L += ["", "### Problem Statement", ""]
    L.append(await _text("problem_statement"))

    L += ["", "### Context Map", ""]
    L += [
        "| Dimension | Detail |",
        "|-----------|--------|",
    ]
    for r in await _rows(CbContextMap):
        L.append(f"| **{_esc(r.dimension)}** | {_esc(r.detail)} |")

    # ── 2. Value Hypothesis & Expected Outcomes ───────────────────────────────
    section("## 2. Value Hypothesis & Expected Outcomes")

    vh_if = await _text("value_hypothesis_if")
    vh_then = await _text("value_hypothesis_then")
    L += [
        "### Value Hypothesis",
        "",
        f"> **If** {_esc(vh_if)}",
        ">",
        f"> **then** {_esc(vh_then)}",
        "",
        "### Expected Outcomes",
        "",
        "| # | Outcome | Description |",
        "|:-:|---------|-------------|",
    ]
    for i, r in enumerate(await _rows(CbOutcome), 1):
        L.append(f"| {i} | **{_esc(r.outcome)}** | {_esc(r.description)} |")

    # ── 3. Success Metrics ────────────────────────────────────────────────────
    section("## 3. Success Metrics")

    L += [
        "| # | Metric | Description | Quantifiable |",
        "|:-:|--------|-------------|:------------:|",
    ]
    for i, r in enumerate(await _rows(CbMetric), 1):
        q = "✓" if r.quantifiable else ""
        L.append(f"| {i} | **{_esc(r.metric)}** | {_esc(r.description)} | {q} |")

    # ── 4. Proposed Capabilities ──────────────────────────────────────────────
    section("## 4. Proposed Capabilities")

    L += [
        "| # | Capability | Description |",
        "|:-:|------------|-------------|",
    ]
    for i, r in enumerate(await _rows(CbCapability), 1):
        L.append(f"| {i} | **{_esc(r.capability)}** | {_esc(r.description)} |")

    # ── 5. Scope Boundaries & Assumptions ─────────────────────────────────────
    scope_rows = await _rows(CbScopeItem)
    in_scope   = [r for r in scope_rows if r.kind == "in_scope"]
    out_scope  = [r for r in scope_rows if r.kind == "out_of_scope"]
    assumptions = [r for r in scope_rows if r.kind == "assumption"]

    section("## 5. Scope Boundaries & Assumptions")

    L += ["### ✅ In Scope", ""]
    for r in in_scope:
        L.append(f"- {r.text}")

    L += ["", "### ❌ Out of Scope", ""]
    for r in out_scope:
        L.append(f"- {r.text}")

    L += ["", "### ⚠️ Assumptions", ""]
    for r in assumptions:
        L.append(f"> {r.text}")
        L.append(">")
    if assumptions:
        L.pop()  # remove trailing >

    # ── 6. Delivery Approach ──────────────────────────────────────────────────
    section("## 6. Delivery Approach")

    L += [
        "| # | Milestone | Target | Description |",
        "|:-:|-----------|--------|-------------|",
    ]
    for i, r in enumerate(await _rows(CbMilestone), 1):
        L.append(f"| {i} | **{_esc(r.milestone)}** | {_esc(r.target)} | {_esc(r.description)} |")

    # ── 7. Approval Gate ──────────────────────────────────────────────────────
    section("## 7. Approval Gate")

    L += [
        "| Criterion | Status | Notes |",
        "|-----------|:------:|-------|",
    ]
    for r in await _rows(CbGateCriterion):
        status_icon = "✅" if r.gate_status == "Approved" else ("⏳" if r.gate_status == "Pending" else "❌")
        L.append(f"| {_esc(r.criterion)} | {status_icon} {_esc(r.gate_status)} | {_esc(r.notes)} |")

    # ── Footer ────────────────────────────────────────────────────────────────
    L += [
        "",
        "---",
        "",
        f"*Generated by [SpecForge](https://specforge.ai) · Concept Brief Builder · {now}*",
    ]

    return "\n".join(L)
