"""BRD_CONTEXT_PROJECTION: static map proving every CB element reaches ≥1 BRD unit.

Also provides CoverageReport for runtime coverage validation.
"""
from __future__ import annotations

from dataclasses import dataclass


# ── Static projection map ─────────────────────────────────────────────────────
# Maps: cb_element_key → list[brd_unit_key]
# Every CB element must appear here. If a CB row type has no BRD unit consuming
# it, that's a coverage gap and validate() will fail.

BRD_CONTEXT_PROJECTION: dict[str, list[str]] = {
    # cb_text_blocks
    "business_context":          ["business_context", "problem_statement"],
    "problem_statement":         ["problem_statement", "objectives", "business_requirements"],
    "value_hypothesis_if":       ["objectives", "business_requirements", "kpis"],
    "value_hypothesis_then":     ["objectives", "kpis"],
    # cb_context_map (fixed dimensions)
    "context_map.business_unit":       ["business_context", "stakeholders"],
    "context_map.new_channel":         ["scope", "business_requirements"],
    "context_map.customer_segments":   ["stakeholders", "actors"],
    "context_map.current_gap":         ["problem_statement", "asis_process", "risks"],
    "context_map.strategic_driver":    ["business_context", "objectives"],
    "context_map.engagement_goal":     ["objectives", "kpis"],
    # cb_outcomes
    "cb_outcomes":                     ["objectives", "business_requirements", "kpis"],
    # cb_metrics
    "cb_metrics":                      ["kpis", "business_requirements"],
    # cb_capabilities
    "cb_capabilities":                 ["business_requirements", "scope", "tobe_process"],
    # cb_scope_items
    "cb_scope_items.in_scope":         ["scope", "business_requirements"],
    "cb_scope_items.out_of_scope":     ["scope", "risks"],
    "cb_scope_items.assumption":       ["assumptions", "risks"],
    # cb_milestones
    "cb_milestones":                   ["implementation_phases", "milestones"],
    # discover Q&A
    "discover_qa":                     [
        "business_context", "objectives", "stakeholders",
        "business_requirements", "risks", "milestones",
    ],
}


@dataclass
class CoverageEntry:
    cb_element_key: str
    brd_units: list[str]
    is_covered: bool          # True when ≥1 target unit has rows
    uncovered_reason: str | None


@dataclass
class CoverageReport:
    entries: list[CoverageEntry]
    covered_count: int
    total_count: int
    all_covered: bool
    uncovered_keys: list[str]


def compute_coverage(unit_row_counts: dict[str, int]) -> CoverageReport:
    """Check that every CB projection element maps to at least one BRD unit with rows.

    unit_row_counts: {unit_key → number of rows generated by that unit}
    """
    entries: list[CoverageEntry] = []
    for cb_key, brd_units in BRD_CONTEXT_PROJECTION.items():
        covered = any(unit_row_counts.get(u, 0) > 0 for u in brd_units)
        entries.append(CoverageEntry(
            cb_element_key=cb_key,
            brd_units=brd_units,
            is_covered=covered,
            uncovered_reason=None if covered else f"No rows generated by {', '.join(brd_units)}",
        ))

    covered_count = sum(1 for e in entries if e.is_covered)
    uncovered_keys = [e.cb_element_key for e in entries if not e.is_covered]

    return CoverageReport(
        entries=entries,
        covered_count=covered_count,
        total_count=len(entries),
        all_covered=len(uncovered_keys) == 0,
        uncovered_keys=uncovered_keys,
    )
